### ISSUE TITLE
Avoid forking repo

### ISSUE THREAD

**Issue by gitfool** [dependabot/dependabot-script#402]
I'm using this script with a privately hosted GitLab instance. I've created a Dependabot user and given it access to the repositories it's monitoring.

With the above in mind, it would be really nice if Dependabot  could submit a MR/PR directly rather than forking the repo first. Is that possible?

**Comment by fmasa** [comment]
@gitfool Does user used by Dependabot has write access to repository? We use Dependabot with several repositories in our privately hosted Gitlab instance and Dependabot creates branches in original repository.

**Comment by jeff-cook** [comment]
I think you're asking about forking the https://github.com/dependabot/dependabot-script repo. 

I'm just starting with this myself, but it looks like no you need to fork (or mirror) it yourself. 
You create a new project that builds it into a Docker image itself.
I'm looking at that to save the time of `bundle install -j $(nproc) --path vendor` for each pipeline. 

I did plan a way to just include this in each project pipeline directly using `include`.
This could possibly be direct from the GitHub repo (without a fork).
The downside I found was every project you scan would need your API token. 
If you fork and schedule then only the bot project needs the token.

**Comment by jeffwidman** [comment]
This repo is primarily a collection of example scripts _if_ you wish to run Dependabot outside of GitHub... it's a starting place, not expected to be production grade as users have all kinds of custom scenarios. 

So forking in order to customize is almost inevitable. That said, there are some ways around that, as others have detailed above. 

Closing, as nothing more to do here.
