### ISSUE TITLE
Execution for `docker` takes very long

### ISSUE THREAD

**Issue by MalteHei** [dependabot/dependabot-script#840]
Hello, I am currently evaluating Dependabot on a GitLab CE instance and found that jobs for package managers `maven` and `npm` generally finish in less than 3 minutes.

However, when running the generic script with `PACKAGE_MANAGER_SET` set to `docker` against the dependabot-script repository itself, the job takes 20+ minutes to finish.
Most of this time is spent executing `bundle exec ruby ./generic-update-script.rb` without outputting anything. Though, after logging `Fetching docker dependency files for <PROJECT_PATH>`, it takes almost no time for the script to finish.

**Comment by jeffwidman** [comment]
Unfortunately, support for other environments isn't something that the main Dependabot team is able to help with currently... we're happy to merge PR's to the `dependabot-script` repo as a shared braintrust for the community to leverage, but we don't have currently have the time to help with further debugging.

Partially that's because we are a small team and currently buried with `dependabot-core` issues, and partially because we're focusing some dev efforts on architecture improvements that we hope will make it easier for folks to run dependabot itself in various environments, rather than having a single script that tries to handle all edge cases for all environments.

One thing you could try is running the `dry-run` script to see if the problem is at the `dependabot-script` layer, or within `dependabot-core`... and then from there it's not hard to start adding additional `puts` statements in the ruby code to start to isolate exactly where the slowdown is coming from. If you do find a specific bug rather than a general "it's slow" issue, then feel free to open a new issue explaining where/what the problem is.
